<!doctype html>
<html lang="ja">
<head>
	<meta charset="utf-8">
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
	<title>onepiece-framework's develop environment</title>
</head>
<body>
<p>onepiece-framework's develop environment</p>
<?php
if( $file = ifset($_GET['file']) ){
	include("{$file}.php");
}
?>
<ol>
	<li><a href="?file=phpinfo">phpinfo</a></li>
	<li><a href="?file=mark">mark</a></li>
	<li><a href="?file=dump">dump</a></li>
	<li><a href="?file=path">path</a></li>
	<li><a href="?file=notice">notice</a></li>
	<li><a href="?file=time">time</a></li>
	<li><a href="?file=database">database</a></li>
	<li><a href="?file=sql">sql</a></li>
</ol>
</body>
</html>