<?php
/**
 * develop:/index.phtml
 *
 * @created   2016-06-09
 * @version   1.0
 * @package   develop
 * @author    Tomoaki Nagahara <tomoaki.nagahara@gmail.com>
 * @copyright Tomoaki Nagahara All right reserved.
 */
//	file list.
$file_list = ['phpinfo','functions','mark','dump','path','notice','notice-mail',
		'env','onepiece','time','session','cookie','template','layout',
		'database','sql','form','japan'
	];
?>
<!doctype html>
<html lang="ja">
<head>
	<meta charset="utf-8" />
	<meta name="viewport" content="width=device-width,initial-scale=1" />
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />

	<title>onepiece-framework's develop environment</title>
</head>
<body>
<p>onepiece-framework's develop environment</p>
<?php
if( $file = ifset($_GET['file']) ){
	if( strpos($file, '.') !== false ){
		D("Wrong file name. ($file)");
	}else{
		//	...
		$file_name = "{$file}.php";
		if( file_exists($file_name) ){
			//	mono page.
			Template::Run($file_name);
		}else{
			//	sub directory.
			$file_name = "{$file}/index.php";
			if( file_exists($file_name) ){
				Template::Run($file_name);
			}else{
				Html::E("Does not found this file. ($file)");
			}
		}
	}
}
?>
<ol>
	<?php foreach($file_list as $key): ?>
		<li><a href="?file=<?= $key ?>"><?= $key ?></a></li>
	<?php endforeach; ?>
</ol>
<script type="text/javascript" src="./import-js.php"></script>
<link rel="stylesheet" type="text/css" href="./import-css.php">
</body>
</html>